import com.loyalty.topic1.model.GroupModel;
import com.loyalty.topic1.model.ConditionModel;
import com.loyalty.topic1.model.CustomerAttributeModel;
import com.loyalty.topic1.model.AttributeModel;
import com.loyalty.topic1.model.OperatorModel;

function boolean checkCondition(String attributeValue, OperatorModel operator, String conditionValue) {
    double attributeDouble = Double.parseDouble(attributeValue);
    double conditionDouble = Double.parseDouble(conditionValue);

    switch (operator.getNotation()) {
        case ">":
            return attributeDouble > conditionDouble;
        case "<":
            return attributeDouble < conditionDouble;
        case "=":
            return attributeValue.equals(conditionValue);
        case ">=":
            return attributeDouble >= conditionDouble;
        case "<=":
            return attributeDouble <= conditionDouble;
        default:
            throw new IllegalArgumentException("Unsupported operator: " + operator.getNotation());
    }
}

rule "check customer attribute"
    when
        $customerAttribute: CustomerAttributeModel($customerId: id.customerId, $attributeId: id.attributeId, $value: value)
        $group: GroupModel(conditionModel != null, labelModel != null)
        $condition: ConditionModel() from $group.getConditionModel
        $operator: OperatorModel() from $condition.getOperatorModel
        eval($condition.getAttributeModel().getAttribute_id() == $attributeId)
        eval(checkCondition($value, $operator, $condition.getValue()))
    then
        System.out.println("Customer with ID " + $customerId + " thỏa mãn điều kiện trong " + $group.getGroup_id() + "\nvới điều kiện là: " + $condition + "\ntrong khi KH có " + $customerAttribute + ". Applying label " + $group.getLabelModel().getLabel_id());
    end

// dynamic loading.....
// salience: xác định độ ưu tiên của các rule, salience nào càng lớn thì được thực hiện trước
// activation-group: Ngăn chặn việc kích hoạt nhiều hơn một rule từ cùng một nhóm (activation group) trong một lần chạy.
                  //Cách sử dụng: Khi một rule trong activation group được kích hoạt,
                  //   các rule khác trong cùng activation group sẽ bị ngăn chặn và không được kích hoạt trong lần chạy hiện tại.
//  agenda-group: Quản lý thứ tự thực thi của các rule và chạy nhóm rule cụ thể theo yêu cầu.
                  // Cách sử dụng: Khi một rule thuộc một agenda group được kích hoạt,
                   //chỉ những rule trong cùng agenda grou p đó mới được thêm vào agenda để thực thi.
//  ruleflow-group: Được sử dụng trong ngữ cảnh của quy trình luồng (rule flow) để quản lý và kiểm soát việc thực thi các rule trong một quy trình luồng cụ thể.
                    // Cách sử dụng: Khi một quy trình luồng được kích hoạt, chỉ những rule thuộc cùng một rule flow group sẽ được thực thi.